sd_card_path: "/Volumes/F6_SD/"
# My Drive/audio_production/raw_recording_backlog
google_drive_folder_id: "1-Jp0e5ZDqzIpn2PGCg0Ht_Mb54PqxySF"
service_json_path: "/Users/q/aia-process-audio-files-aea720c2415f.json"
mic:
  Tr1_2: "NT5s"
  Tr3: "NTG3"
  Tr4: "P220"
creator_id: "AIA"
source_id: "FXLIB"
slate_length: 5
